### ISSUE TITLE
[BUG] Unable to manage file: Jinja error: openvpn/macros.jinja using salt-ssh

### ISSUE THREAD

**Issue by waynegemmell** [saltstack-formulas/openvpn-formula#147]
### Formula commit hash / release tag

I'm using HEAD on master

### Versions reports (master & minion)

Sunning salt-ssh
```
Salt Version:
          Salt: 3003rc1+348.gd637879696
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.8.10 (default, Jun  2 2021, 10:49:15)
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 21.0.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.3
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.11.0-37-generic
        system: Linux
       version: Ubuntu 20.04 focal
```

---

### Describe the bug

The following error happens when trying to apply openvpn formula useing salt-ssh.
`Unable to manage file: Jinja error: openvpn/macros.jinja`
I have the following in my Saltfile which normally fixes the issue. 
`      - salt://openvpn/macros.jinja`

Here's the output

```
     Comment: Unable to manage file: Jinja error: openvpn/macros.jinja
              /var/tmp/.salt_6cb4b9_salt/running_data/var/cache/salt/minion/files/base/openvpn/files/common_opts.jinja(1):
              ---
              {% from "openvpn/macros.jinja" import multipart_param with context %}    <======================
              
              {%- if config.daemon is defined and config.daemon == True %}
              daemon
              {%- endif -%}
              
              [...]
              ---
              Traceback (most recent call last):
                File "/var/tmp/.salt_6cb4b9_salt/pyall/salt/utils/templates.py", line 501, in render_jinja_tmpl
                  output = template.render(**decoded_context)
                File "/var/tmp/.salt_6cb4b9_salt/pyall/jinja2/environment.py", line 1090, in render
                  self.environment.handle_exception()
                File "/var/tmp/.salt_6cb4b9_salt/pyall/jinja2/environment.py", line 832, in handle_exception
                  reraise(*rewrite_traceback_stack(source=source))
                File "/var/tmp/.salt_6cb4b9_salt/pyall/jinja2/_compat.py", line 28, in reraise
                  raise value.with_traceback(tb)
                File "<template>", line 5, in top-level template code
                File "/var/tmp/.salt_6cb4b9_salt/running_data/var/cache/salt/minion/files/base/openvpn/files/common_opts.jinja", line 1, in top-level template code
                  {% from "openvpn/macros.jinja" import multipart_param with context %}
                File "/var/tmp/.salt_6cb4b9_salt/pyall/salt/utils/jinja.py", line 198, in get_source
                  raise TemplateNotFound(template)
              jinja2.exceptions.TemplateNotFound: openvpn/macros.jinja
```

**Comment by myii** [comment]
Thanks for this report, @waynegemmell.  This is strange, since we have the newest `map.jinja` implementation in place here, which was fully tested on `salt-ssh` as it was put together.

@baby-gnu Any ideas about what is happening here?

**Comment by baby-gnu** [comment]
Hello @myii and @waynegemmell.

I just made a simple test:

1. setup a [`salt-ssh` configuration](https://gist.github.com/baby-gnu/8a198629161fe8fc60bd2b33a8321012)
2. clone `openvpn-formula` to `~/.salt/srv/formulas/openvpn-formula`
2. copy `~/.salt/srv/formulas/openvpn-formula/pillar.example` to `~/.salt/srv/pillar/openvpn.sls`
3. assign that pillar to my target VM
   ```sls
   base:
     'ipv4:192.168.0.101':
       - match: grain
       - openvpn
   ```
4. execute `salt-ssh --output yaml 192.168.0.101 state.show_sls openvpn`, which produce the following output:
   ``` sls
   192.168.0.101:
     obsolete_openvpn_myclient1_service:
       __env__: base
       __sls__: openvpn.service
       service:
       - name: openvpn@myclient1
       - enable: false
       - dead
       - order: 10004
     obsolete_openvpn_myserver1_service:
       __env__: base
       __sls__: openvpn.service
       service:
       - name: openvpn@myserver1
       - enable: false
       - dead
       - order: 10002
     openvpn_create_dh_512:
       __env__: base
       __sls__: openvpn.dhparams
       cmd:
       - name: '"openssl" dhparam -out "/etc/openvpn/server/dh512.pem" 512'
       - creates: /etc/openvpn/server/dh512.pem
       - require:
         - pkg: openvpn_pkgs
       - run
       - order: 10001
     openvpn_myclient1_service:
       __env__: base
       __sls__: openvpn.service
       service:
       - name: openvpn-client@myclient1
       - enable: true
       - require:
         - pkg: openvpn_pkgs
         - sls: openvpn.install
       - running
       - order: 10005
     openvpn_myserver1_service:
       __env__: base
       __sls__: openvpn.service
       service:
       - name: openvpn-server@myserver1
       - enable: true
       - require:
         - pkg: openvpn_pkgs
         - sls: openvpn.install
       - running
       - order: 10003
     openvpn_pkgs:
       __env__: base
       __sls__: openvpn.install
       pkg:
       - pkgs:
         - openvpn
       - installed
       - order: 10000
   ```

<details><summary>salt-ssh --versions-report</summary>

```
Salt Version:
          Salt: 3002.6
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.9.7
        pygit2: Not Installed
        Python: 3.9.7 (default, Sep 24 2021, 09:43:00)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 22.2.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian unstable sid
        locale: utf-8
       machine: x86_64
       release: 5.14.0-2-amd64
        system: Linux
       version: Debian GNU/Linux unstable sid
```
</details>

I even try a `state.apply`.

<details><summary>salt-ssh 192.168.0.101 state.apply openvpn</summary>

```
192.168.0.101:
----------
          ID: openvpn_pkgs
    Function: pkg.installed
      Result: True
     Comment: The following packages were installed/updated: openvpn
     Started: 15:55:26.027672
    Duration: 3306.577 ms
     Changes:   
              ----------
              liblzo2-2:
                  ----------
                  new:
                      2.10-2
                  old:
              libpkcs11-helper1:
                  ----------
                  new:
                      1.27-1
                  old:
              openvpn:
                  ----------
                  new:
                      2.5.1-3
                  old:
----------
          ID: openvpn_create_dh_512
    Function: cmd.run
        Name: "openssl" dhparam -out "/etc/openvpn/server/dh512.pem" 512
      Result: True
     Comment: Command ""openssl" dhparam -out "/etc/openvpn/server/dh512.pem" 512" run
     Started: 15:55:29.340243
    Duration: 1803.244 ms
     Changes:   
              ----------
              pid:
                  15730
              retcode:
                  0
              stderr:
                  Generating DH parameters, 512 bit long safe prime, generator 2
                  This is going to take a long time
                  .....................................+.......+............................+.........+................+........+................................+.......+..................................+.................................+...+...+..........................................................................+.......+..........+...................+..........................+.+..............+...................+....................................+....................+.....................................+..............+..............+..........+.....................+.....+.....................+.......................++*++*++*++*++*
              stdout:
----------
          ID: obsolete_openvpn_myserver1_service
    Function: service.dead
        Name: openvpn@myserver1
      Result: True
     Comment: The service openvpn@myserver1 is already dead
     Started: 15:55:31.143768
    Duration: 39.757 ms
     Changes:   
----------
          ID: openvpn_myserver1_service
    Function: service.running
        Name: openvpn-server@myserver1
      Result: False
     Comment: Job for openvpn-server@myserver1.service failed because the control process exited with error code.
              See "systemctl status openvpn-server@myserver1.service" and "journalctl -xe" for details.
     Started: 15:55:31.184283
    Duration: 69.761 ms
     Changes:   
----------
          ID: obsolete_openvpn_myclient1_service
    Function: service.dead
        Name: openvpn@myclient1
      Result: True
     Comment: The service openvpn@myclient1 is already dead
     Started: 15:55:31.254305
    Duration: 36.9 ms
     Changes:   
----------
          ID: openvpn_myclient1_service
    Function: service.running
        Name: openvpn-client@myclient1
      Result: False
     Comment: Job for openvpn-client@myclient1.service failed because the control process exited with error code.
              See "systemctl status openvpn-client@myclient1.service" and "journalctl -xe" for details.
     Started: 15:55:31.291657
    Duration: 69.458 ms
     Changes:   

Summary for 192.168.0.101
------------
Succeeded: 4 (changed=2)
Failed:    2
------------
Total states run:     6
Total run time:   5.326 s
```
</details>

I do not use the `--extra-filerefs` option

**Comment by waynegemmell** [comment]
I've removed the extra-filerefs from my config and it's doing the same thing. Maybe it's a version issue? I'm trying to test on a lower version but not managing.

**Comment by baby-gnu** [comment]
I'll setup a 3003.3 on a VM to test.

**Comment by baby-gnu** [comment]
Hello, https://github.com/saltstack/salt/pull/61895 fixes my issues with either `rootfs` and `gitfs` without the any use of `--extra-filerefs`.
